### ISSUE TITLE
Administration Page

### ISSUE THREAD

**Issue by Iron-Mike-Tyson** [dotnet-da/group_1#45]
- Anzeige aller Accounts in Tabelle
- Wenn Account ausgewählt wird, in separater Tabelle alle dazugehörigen Logs laden
- Wenn Account ausgewählt wird, in separater Tabelle alle dazugehörigen Watchlists laden
- Möglichkeit neuen Account in die Datenbank zu schreiben
- Möglichkeit Account Daten zu bearbeiten
- Möglichkeit Account zu löschen

**Comment by T-hai** [comment]
In Progress in branch 23-admin-view
